### ISSUE TITLE
怎样通过api来执行一个特定task？

### ISSUE THREAD

**Issue by medmin** [clock-sh/ticket#1]
您好

我想通过api来触发某个task
但一方面您的文档暂时没写太清楚，不知道具体哪个api
二方面，怎样才能看到task的id？ 

谢谢

**Comment by laixintao** [comment]
Hi 抱歉回复晚了。暂时没有办法触发一个特定的task，只有时间可以触发。
API 还不太成熟，开发精力有限，我会先开发功能，和提供API，后面再完善API和文档。
