### ISSUE TITLE
add requests for python3 environment?

### ISSUE THREAD

**Issue by zjuchenyuan** [clock-sh/ticket#2]
Could you add package `requests` for the environment? This will save the time spent on running `os.system("pip install requests")` over and over again.

One more step, the user can specify desired packages, then the server will build a correspoding docker image for this task.

Thanks~

**Comment by laixintao** [comment]
Thanks for the advice!

Lots of users want a costume docker image build process, the difficulty is, the workers are distributed, I need to figure out what's the best way for a worker to download the docker image then run it. And worker can't keep a docker image too long, the different images will cause worker out of disk space.

But I will get this feature online ASAP. (manbe in 1 month)

I will leave this issue open.
