### ISSUE TITLE
任务没有执行

### ISSUE THREAD

**Issue by Steve662024** [clock-sh/ticket#7]
![image](https://user-images.githubusercontent.com/25817975/98655695-b7b4e500-237a-11eb-9ca6-bb8b64135560.png)

id为406的task，显示 Runs on: Every 10 minutes，但是Executions为空，没有任何执行信息，麻烦帮忙看下是什么问题，感谢！

**Comment by laixintao** [comment]
任务实际上应该是执行的了，只不过没有保存执行记录。

**Comment by laixintao** [comment]
我重新拉起来了，过段时间你再看看是否有执行记录

**Comment by Steve662024** [comment]
已经好了，感谢！
